stages:
#  - lint
  - test
  - security
  - deploy

#lint: # check code styles and type hints
#  stage: lint
#  image: python:3.9
#  before_script:
#    - apt-get update
#    - apt-get install -y python3 python3-pip
#  script:
#    - pip install flake8 mypy
#    - flake8 .
#    - mypy .

test:
  stage: test
  image: python:3.9
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: notadmin
    POSTGRES_PASSWORD: 1
  before_script:
    - cd gap_project/
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python manage.py makemigrations --merge
    - python manage.py migrate
  script:
    - python manage.py test
    - coverage run --source='.' manage.py test
    - coverage report

#security:
#  stage: security
#  script:
#    - pip install bandit safety
#    - bandit -r .
#    - safety check

deploy:
  stage: deploy
  script:
    - echo "Deploy script here"