stages:
  - lint
  - test
  - security
  - deploy

lint-backend:
  stage: lint
  image: python:3.12
  before_script:
    # - apt-get update
    # - apt-get install -y python3 python3-pip
    - pip install flake8 mypy
  script:
    - flake8 . # Formatting issues, unused imports, indentation errors
    - mypy . # Type mismatches, incorrect return types

lint-frontend:
  stage: lint
  image: node:22.11
  script:
    - npm install -g eslint
    - npx eslint . # --max-warnings=0 #(This makes the pipeline fail if styling errors detected)

test:
  stage: test
  image: python:3.12
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: GAPAdmin
    POSTGRES_PASSWORD: 1
  before_script:
    - apt-get update
    - apt-get install -y python3 python3-pip
    - pip install django djangorestframework django-cors-headers coverage
    - cd gap_project/
    - python manage.py makemigrations --merge
    - python manage.py migrate
  script:
    - python manage.py test
    - coverage run --source='.' manage.py test
    - coverage report

#security:
#  stage: security
#  script:
#    - pip install bandit safety
#    - bandit -r .
#    - safety check

deploy:
  stage: deploy
  script:
    - echo "Deploy script here"