services:
    backend:
        image: docker.io/gordon-foley:backend
    build:
        context: ./gap_project
        dockerfile: DockerFile
    container_name: backend
    ports:
        - "8000:8000"
    enviroment:
        - DB_URL=postgresql://gordonfoley:mA5AB0YUZX5aleqCs5FKtxAWlh3EnXdc@dpg-cv10jbqj1k6c73arogc0-a.frankfurt-postgres.render.com/gordonfoleydb
        - DB_NAME=gordon-foley-database
        - DB_USER=gordonfoley
        - BD_PASSWORD=mA5AB0YUZX5aleqCs5FKtxAWlh3EnXdc
        - DB_HOST=dpg-cv10jbqj1k6c73arogc0-a
    depends_on:
        - frontend
    command: [
        "sh",
        "-c",
        "python manage.py makemigrations 
        && python manage.py migrate
        && python populate.py
        && gunicorn --bind 0.0.0:8000 gap_project.wsgi:application"
    ]

frontend:
    image: $docker.io/gordon-foley:frontend
    container_name: frontend
    build:
        context: ./gap_project/frontend
        dockerfile: DockerFile
        args:
            REACT_APP_BACKEND_URL: ${BACKEND_URL}
            REACT_APP_FRONTEND_URL: ${FRONTEND_URL}
    ports:
        - "3000:80"
    depends_on:
        - backend