FROM node:18-alpine AS frontend

# set working directory
WORKDIR /gap_project

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# copy rest of frontend files
COPY . .

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

ARG REACT_APP_FROMTEND_URL
ENV REACT_APP_FRONTEND_URL=${REACT_APP_FRONTEND_URL}

RUN npm run build || (echo "frontend build failed" && exit 1)

# serve with NGINX
FROM nginx:alpine

RUN rm /etc/nginx/conf. d/default.conf

COPY ngix.conf /etc/nginx/conf .d/default.conf

COPY --from=frontend /gap_project/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]