# Generated by Django 4.2.16 on 2024-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gap", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company", options={"verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="gapanalysis", options={"verbose_name_plural": "Gap Analyses"},
        ),
        migrations.AddField(
            model_name="gapanalysis",
            name="title",
            field=models.CharField(
                default="Gap Analysis : <django.db.models.fields.DateField>",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="dateRegistered",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="gapanalysis",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
