# Generated by Django 4.2.16 on 2024-11-17 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gap", "0003_remove_gapanalysis_url_gapanalysis_gap_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gapanalysis",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
