# Generated by Django 4.2.16 on 2024-11-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gap", "0004_alter_gapanalysis_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gapanalysis",
            name="gap_data",
            field=models.JSONField(default=dict),
        ),
    ]
