# Generated by Django 5.1.3 on 2024-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gap", "0005_alter_gapanalysis_gap_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
