# Generated by Django 5.1.3 on 2025-01-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0006_company_notes'),
        ('gap', '0006_gapanalysis_improvement_plan_userprofile'),
    ]

    operations = [
    ]
