# Generated by Django 5.1.5 on 2025-01-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0007_merge_20250115_1231'),
        ('gap', '0007_score'),
    ]

    operations = [
    ]
