# Generated by Django 5.1.3 on 2025-01-29 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0007_merge_20250115_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='current_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='additionalNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='companyEmail',
            field=models.EmailField(default="companyemail@email.com", max_length=128),
        ),
        migrations.AddField(
            model_name='gapanalysis',
            name='companyRep',
            field=models.CharField(default="John Doe", max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('improvement', models.TextField(blank=True, null=True)),
                ('gap_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='gap.gapanalysis')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='gap.section'),
        ),
    ]
