# Generated by Django 5.1.3 on 2025-01-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0008_question_section_alter_company_dateregistered_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dateRegistered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
