# Generated by Django 5.1.3 on 2025-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0008_question_section_company_current_gap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dateRegistered',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gapanalysis',
            name='companyEmail',
            field=models.EmailField(default=None, max_length=128),
        ),
    ]
