# Generated by Django 5.1.3 on 2025-02-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0010_alter_gapanalysis_companyemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapanalysis',
            name='url',
            field=models.URLField(default='no url given'),
        ),
    ]
