# Generated by Django 5.1.5 on 2025-02-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0008_merge_0007_merge_20250115_1231_0007_score'),
        ('gap', '0010_alter_gapanalysis_companyemail'),
    ]

    operations = [
    ]
