# Generated by Django 5.1.3 on 2025-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0011_merge_20250212_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AlterField(
            model_name='gapanalysis',
            name='title',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>-Gap Analysis<django.db.models.fields.DateField>', max_length=50),
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
