# Generated by Django 5.1.5 on 2025-03-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0012_rename_dateregistered_company_date_registered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gapanalysis',
            old_name='companyEmail',
            new_name='company_email',
        ),
        migrations.RenameField(
            model_name='gapanalysis',
            old_name='companyRep',
            new_name='company_rep',
        ),
    ]
