# Generated by Django 5.1.5 on 2025-03-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0013_rename_companyemail_gapanalysis_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gapanalysis',
            old_name='additionalNotes',
            new_name='additional_notes',
        ),
    ]
